### PR TITLE
HTTP lookups for c++ client lib

### PR DESCRIPTION
**Pull request by jai1**
### Motivation

Want to reintroduce HTTP Lookup in order to maintain seamless production rollout

### Modifications

Couldn't use URDL hence created a HTTPWrapper over asio

### Result

HTTPLookup possible.

### TODO - Remaining
a. Remove mentions of YCA from the code

### CODE REVIEW

File: pulsar-client-cpp/lib/HTTPWrapper.cc [hunk 1]
```diff
@@ -0,0 +1,241 @@
...
+            inputStream >> response_.content;
+            boost::asio::async_read(*socketPtr_, *responseStreamPtr_,
+                                    boost::asio::transfer_at_least(1),
+                                    boost::bind(&HTTPWrapper::handle_read_content, shared_from_this(),
+                                                boost::asio::placeholders::error));
+        } else if (err == boost::asio::error::eof) {
+            // eof occurs but responseStreamPtr_ not necessarily emptys
+            LOG_DEBUG("EOF occured");
+            std::istream inputStream(responseStreamPtr_.get());
+            inputStream >> response_.content;
```
Comment (msb-at-yahoo) [inline pulsar-client-cpp/lib/HTTPWrapper.cc]: is the intent to read all of the stream content and store into response_.content?  this only reads the first whitespace delimited string.  try this:

```
std::ostringstream os;
os << inputStream.rdbuf();
response_.content = os.str();
```

File: pulsar-client-cpp/lib/HTTPWrapper.cc [hunk 2]
```diff
@@ -0,0 +1,241 @@
...
+            response_.errCode = err;
+            response_.retCode = Response::Success;
+            callback_(shared_from_this());
+        } else {
+            response_.errCode = err;
+            response_.retCode = Response::ResponseFailure;
+            callback_(shared_from_this());
+        }
+    }
+}
```
Comment (msb-at-yahoo) [inline pulsar-client-cpp/lib/HTTPWrapper.cc]: missing newline

File: pulsar-client-cpp/lib/HTTPWrapper.cc [hunk 3]
```diff
@@ -0,0 +1,241 @@
...
+#include "HTTPWrapper.h"
+
+DECLARE_LOG_OBJECT()
+
+namespace pulsar {
+    using boost::asio::ip::tcp;
+    static const HTTPWrapper::Response EMPTY_RESPONSE = HTTPWrapper::Response();
+
+    static void removeCarriage(std::string& str) {
+        str.erase( std::remove(str.begin(), str.end(), '\r'), str.end() );
```
Comment (msb-at-yahoo) [inline pulsar-client-cpp/lib/HTTPWrapper.cc]: this removes all '\r' occurrences in the string, but in all of the places you use it, there's only one at the end of the line, right?

**Comment by merlimat** [comment]
> what was the issue you ran into with using curl? integrating with the asio event loop?

@msb-at-yahoo @jai1 Integrating with asio should not be impossible. You could have a thread pool running libcurl in blocking way and then notifying the completion by "posting" work on the asio event loop thread.

File: pulsar-client-cpp/lib/HTTPWrapper.cc [hunk 4]
```diff
@@ -0,0 +1,241 @@
...
+        os << ", error_code = " << obj.errCode << "\n";
+        os << "}]";
+        return os;
+    }
+
+    HTTPWrapper::HTTPWrapper(ExecutorServiceProviderPtr executorServiceProviderPtr)
+            : executorServiceProviderPtr_(executorServiceProviderPtr){
+    }
+
+    std::string HTTPWrapper::getHTTPMethodName(const Request::Method& method) {
```
Comment (jai1) [inline pulsar-client-cpp/lib/HTTPWrapper.cc]: Not making this change since if we don't copy the returned result the underlying object is deleted

#include <iostream>
using namespace std;
const int& get1() {
    int i = 1;
    return i;
}


int main() {
    int a = get1();
//    int &b = get1();// compilation error since we drop the const
    const int &c = get1();
    cout<<a<<endl;
    cout<<c<<endl;
}

**./a.out**
1
32767

File: pulsar-client-cpp/lib/HTTPWrapper.cc [hunk 5]
```diff
@@ -0,0 +1,241 @@
...
+        }
+    }
+
+    void HTTPWrapper::handle_read_headers(const boost::system::error_code &err) {
+        // boost::asio::error::eof not handles since HTTP format don't expect EOF before \r\n\r\n
+        if (!err) {
+            std::istream inputStream(responseStreamPtr_.get());
+            std::string header;
+            // response_.headers guaranteed to have atleast one string since reserve called
+            while (std::getline(inputStream, header) && header != "\r") {
```
Comment (jai1) [inline pulsar-client-cpp/lib/HTTPWrapper.cc]: Added in the header

File: pulsar-client-cpp/lib/HTTPWrapper.cc (hunk 2 above)
Comment (jai1) [inline pulsar-client-cpp/lib/HTTPWrapper.cc]: Done

**Comment by jai1** [comment]
@merlimat @msb-at-yahoo @saandrews  - curl works with asio (example below) but getting it work with boost::asio 1.41 was a bit difficult since few methods are not supported in the old version and also in the standup there was an issue of not liking libcurl so I abandoned the effort.

Anyways, I will spend some more time on this and try to get the old asio to work with libcurl.

https://curl.haxx.se/libcurl/c/asiohiper.html

**Comment by merlimat** [comment]
@jai1 I don't think that making curl to use asio underneath is necessary. That might be much more difficult than just using a thread pool and normal blocking libcurl calls.

**Comment by msb-at-yahoo** [comment]
the only thing we'd need of asio is a way to plug in the curl fds into the epoll loop.

having a queue and using the "easy curl" interface from a background thread is reasonable, too. it'd have the benefit of providing a natural rate limit

**Comment by merlimat** [comment]
> having a queue and using the "easy curl" interface from a background thread is reasonable, too. it'd have the benefit of providing a natural rate limit

I think it would be easier to do and anyway we have already another mechanism to do efficient lookups with the binary protocol, so I wouldn't put a big emphasis on performance HTTP lookup at this point.

File: pulsar-client-cpp/lib/HTTPLookupService.cc [hunk 6]
```diff
@@ -0,0 +1,206 @@
...
+    LookupDataResultPtr HTTPLookupService::parseLookupData(const std::string &json) {
+        Json::Value root;
+        Json::Reader reader;
+        if (!reader.parse(json, root, false)) {
+            LOG_ERROR("Failed to parse json : " << reader.getFormatedErrorMessages()
+                    << "\nInput Json = " << json);
+            return LookupDataResultPtr();
+        }
+        const std::string defaultNotFoundString = "Url Not found";
+        const std::string brokerUrl = root.get("brokerUrl", defaultNotFoundString).asString();
```
Comment (jai1) [inline pulsar-client-cpp/lib/HTTPLookupService.cc]: Used get instead of find since the json_cpp version in yahoo env doesn't support the find API.

File: pulsar-client-cpp/CMakeLists.txt [hunk 7]
```diff
@@ -32,6 +32,11 @@ find_library(LOG4CXX_LIBRARY_PATH log4cxx)
 find_library(CURL_LIBRARY_PATH curl)
 find_path(LOG4CXX_INCLUDE_PATH log4cxx/logger.h)
 find_path(GTEST_INCLUDE_PATH gtest/gtest.h)
+find_library(LIB_JSON jsoncpp)
```
Comment (merlimat) [inline pulsar-client-cpp/CMakeLists.txt]: Can you also update README with the dependency list?

File: pulsar-client-cpp/lib/HTTPLookupService.cc [hunk 8]
```diff
@@ -0,0 +1,206 @@
...
+    lookupTimeoutInSeconds_(clientConfiguration.getOperationTimeoutSeconds()) {
+        if (lookupUrl[lookupUrl.length() - 1] == '/') {
+            // Remove trailing '/'
+            adminUrl_ = lookupUrl.substr(0, lookupUrl.length() - 1);
+        } else {
+            adminUrl_ = lookupUrl;
+        }
+
+        // Once per application - https://curl.haxx.se/mail/lib-2015-11/0052.html
+        curl_global_init(CURL_GLOBAL_ALL);
```
Comment (merlimat) [inline pulsar-client-cpp/lib/HTTPLookupService.cc]: If I start 2 pulsar clients, there would be a problem. We need to have some static flag and mutex to ensure this gets executed once.

File: pulsar-client-cpp/lib/Url.cc [hunk 9]
```diff
@@ -81,4 +83,22 @@ const int Url::port() const {
     return port_;
 }
 
+const std::string& Url::path() const {
+    return path_;
+}
+
+const std::string& Url::file() const {
```
Comment (merlimat) [inline pulsar-client-cpp/lib/Url.cc]: What is file in a URL?

Comment (merlimat) [inline pulsar-client-cpp/lib/Url.cc]: Shouldn't that be part of the `path`?

File: pulsar-client-cpp/CMakeLists.txt (hunk 7 above)
Comment (jai1) [inline pulsar-client-cpp/CMakeLists.txt]: Done

**Comment by jai1** [comment]
@merlimat - I have handled your CR comments - can I please get a +1 
Also for the URL part:-
The legacy code Url.cc:42 regex was designed for handling URLs of type http://test.example.com/dir/subdir/file.html?arg1=var1,arg2=var2

Where path is "/dir/subdir/" and file is "file.html"

File: pulsar-client-cpp/lib/HTTPLookupService.cc [hunk 10]
```diff
@@ -0,0 +1,209 @@
...
+    authenticationPtr_(authData),
+    lookupTimeoutInSeconds_(clientConfiguration.getOperationTimeoutSeconds()) {
+        if (lookupUrl[lookupUrl.length() - 1] == '/') {
+            // Remove trailing '/'
+            adminUrl_ = lookupUrl.substr(0, lookupUrl.length() - 1);
+        } else {
+            adminUrl_ = lookupUrl;
+        }
+        // Once per application - https://curl.haxx.se/mail/lib-2015-11/0052.html
+        Lock lock(curlGlobalMutex_);
```
Comment (merlimat) [inline pulsar-client-cpp/lib/HTTPLookupService.cc]: I don't think this would work either. It just protects 2 threads from calling `curl_global_init()` at the same time, but not at different times. Also we need to keep track of how many Pulsar instances are created, since we can only call the `curl_global_cleanup()` once the last instance is destroyed.

I think the easiest option would be to encapsulate the `curl_global_init / cleanup` within a c++ object managed by a static `shared_ptr` or something like that.

Comment (msb-at-yahoo) [inline pulsar-client-cpp/lib/HTTPLookupService.cc]: you don't need a shared pointer:

```c++
static void globalInit() {
    struct Init {
        Init() { curl_global_init(XXX); }
        ~Init() { curl_global_cleanup(); }
    };

    // required to be thread-safe by C++11, true for GCC >= 3.4.
    // FIXME: someone add a #error here for old versions of MSVC
    static Init init;
}
```

Comment (jai1) [inline pulsar-client-cpp/lib/HTTPLookupService.cc]: I guess this will work

    class HTTPLookupService : public LookupService, public boost::enable_shared_from_this<HTTPLookupService> {
        class CurlInitializer {
         public:
            CurlInitializer() {
                // Once per application - https://curl.haxx.se/mail/lib-2015-11/0052.html
                curl_global_init (CURL_GLOBAL_ALL);
            }
            ~CurlInitializer() {
                curl_global_cleanup();
            }
        };
        static CurlInitializer curlInitializer;

File: pulsar-client-cpp/lib/ExecutorService.cc [hunk 11]
```diff
@@ -68,6 +68,10 @@ void ExecutorService::postWork(boost::function<void(void)> task) {
     io_service_.post(task);
 }
 
+ReadStreamPtr ExecutorService::createReadStream() {
+    return boost::make_shared<boost::asio::streambuf>();
+}
+
```
Comment (saandrews) [inline pulsar-client-cpp/lib/ExecutorService.cc]: If this is unused, we should remove it.
